name: 'GitHub Actions CloudFlare2DNSPod Bot'

on:
  push:
    branches: 
      - master
      
  schedule:
    - cron: '*/16 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 'Install dependencies'
        run: |
          pip install -r requirements.txt
        
      - name: 'Run cf2dns'
        env:
          KEY: ${{ secrets.KEY }}
          DOMAINS: ${{ secrets.DOMAINS }}
          SECRETID: ${{ secrets.SECRETID }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
        run: |
          python cf2dns_actions.py
